version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=blockchain_tracker
      - MORALIS_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6ImM5YWI4NTY2LTkwNDItNDllYS1iYzQxLTAzYWJkNTZmOGYyYSIsIm9yZ0lkIjoiNDE1MjMyIiwidXNlcklkIjoiNDI2NzMxIiwidHlwZSI6IlBST0pFQ1QiLCJ0eXBlSWQiOiJiN2E5MTYxMS03ZjdlLTRjMGMtYWRiNy01Zjk3NjBhNjRlZjgiLCJpYXQiOjE3MzA5NjQxNTYsImV4cCI6NDg4NjcyNDE1Nn0.WYupxMn17aq8Q3YUC-VSUn6JHBBVUho1INZ-H0pMgXE
      - RESEND_API=re_WkLSCyWE_DTwyM7GmzkLZZ5raJXKiaZmf
      - EMAIL_FROM=onboarding@resend.dev

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blockchain_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: