# For local development

version: '3'

services:
  profiler-server:
    container_name: bolide-wallet-profiler-server
    depends_on:
      - profiler-postgress
    build: .
    ports:
      - "3000:3000"
    networks:
      - profiler-net
  grafana:
    container_name: bolide-wallet-profiler-grafana
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    networks:
      - profiler-net
  profiler-postgress:
    container_name: bolide-wallet-profiler-postgress
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src/db/01_init_pg_dbs.sql:/docker-entrypoint-initdb.d/01_init_pg_dbs.sql
      - ./src/db/02_dump.sql:/docker-entrypoint-initdb.d/02_dump.sql
    networks:
      - profiler-net
networks:
  profiler-net:
    name: bolide-wallet-profiler-net